# Generated by Django 5.2 on 2026-02-24 12:20

import random
from django.db import migrations


def update_products_with_images_and_prices(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    
    # Define image mappings based on product names/categories
    image_mappings = {
        'shirt': 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
        'cotton': 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
        'summer': 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
        't-shirt': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
        'jeans': 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
        'pants': 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
        'dress': 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop',
        'shoes': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
        'sneakers': 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
        'jacket': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop',
        'coat': 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&h=400&fit=crop',
        'watch': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
        'bag': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
        'hat': 'https://images.unsplash.com/photo-1574664173527-394226f37b27?w=400&h=400&fit=crop',
        'cap': 'https://images.unsplash.com/photo-1574664173527-394226f37b27?w=400&h=400&fit=crop',
        'glasses': 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=400&fit=crop',
        'sunglasses': 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&h=400&fit=crop',
    }
    
    # Default image for products that don't match any category
    default_image = 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=400&fit=crop'
    
    for product in Product.objects.all():
        # Update price to be between 399 and 2499
        new_price = random.randint(399, 2499)
        product.price = new_price
        
        # Find appropriate image based on product name
        product_name_lower = product.name.lower()
        image_url = default_image
        
        for keyword, url in image_mappings.items():
            if keyword in product_name_lower:
                image_url = url
                break
        
        product.image_url = image_url
        product.save()


def reverse_update_products_with_images_and_prices(apps, schema_editor):
    # This is a data migration, so we don't need to reverse it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customersupportconversation_customersupportmessage'),
    ]

    operations = [
        migrations.RunPython(
            update_products_with_images_and_prices,
            reverse_update_products_with_images_and_prices,
        ),
    ]
