# Generated by Django 5.2 on 2026-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_products_with_images_and_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersupportmessage',
            name='conversation',
        ),
        migrations.AddField(
            model_name='product',
            name='activity_tag',
            field=models.CharField(blank=True, choices=[('gym', 'Gym'), ('hiking', 'Hiking'), ('party', 'Party'), ('travel', 'Travel'), ('casual', 'Casual'), ('formal', 'Formal'), ('beach', 'Beach'), ('sports', 'Sports'), ('business', 'Business'), ('outdoor', 'Outdoor')], help_text='Primary activity this product is designed for', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Optional boost score for ranking'),
        ),
        migrations.AddField(
            model_name='product',
            name='temp_category',
            field=models.CharField(blank=True, choices=[('cold', 'Cold'), ('moderate', 'Moderate'), ('hot', 'Hot')], help_text='Temperature category this product is suitable for', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerSupportConversation',
        ),
        migrations.DeleteModel(
            name='CustomerSupportMessage',
        ),
    ]
